'template/etc' -> './etc'
'template/etc/dionaea' -> './etc/dionaea'
'template/etc/dionaea/ihandlers-available' -> './etc/dionaea/ihandlers-available'
'template/etc/dionaea/ihandlers-available/cmdshell.yaml' -> './etc/dionaea/ihandlers-available/cmdshell.yaml'
'template/etc/dionaea/ihandlers-available/emu_scripts.yaml' -> './etc/dionaea/ihandlers-available/emu_scripts.yaml'
'template/etc/dionaea/ihandlers-available/emuprofile.yaml' -> './etc/dionaea/ihandlers-available/emuprofile.yaml'
'template/etc/dionaea/ihandlers-available/fail2ban.yaml' -> './etc/dionaea/ihandlers-available/fail2ban.yaml'
'template/etc/dionaea/ihandlers-available/ftp.yaml' -> './etc/dionaea/ihandlers-available/ftp.yaml'
'template/etc/dionaea/ihandlers-available/hpfeeds.yaml' -> './etc/dionaea/ihandlers-available/hpfeeds.yaml'
'template/etc/dionaea/ihandlers-available/log_db_sql.yaml' -> './etc/dionaea/ihandlers-available/log_db_sql.yaml'
'template/etc/dionaea/ihandlers-available/log_incident.yaml' -> './etc/dionaea/ihandlers-available/log_incident.yaml'
'template/etc/dionaea/ihandlers-available/log_json.yaml' -> './etc/dionaea/ihandlers-available/log_json.yaml'
'template/etc/dionaea/ihandlers-available/log_sqlite.yaml' -> './etc/dionaea/ihandlers-available/log_sqlite.yaml'
'template/etc/dionaea/ihandlers-available/nfq.yaml' -> './etc/dionaea/ihandlers-available/nfq.yaml'
'template/etc/dionaea/ihandlers-available/p0f.yaml' -> './etc/dionaea/ihandlers-available/p0f.yaml'
'template/etc/dionaea/ihandlers-available/s3.yaml' -> './etc/dionaea/ihandlers-available/s3.yaml'
'template/etc/dionaea/ihandlers-available/store.yaml' -> './etc/dionaea/ihandlers-available/store.yaml'
'template/etc/dionaea/ihandlers-available/submit_http.yaml' -> './etc/dionaea/ihandlers-available/submit_http.yaml'
'template/etc/dionaea/ihandlers-available/submit_http_post.yaml' -> './etc/dionaea/ihandlers-available/submit_http_post.yaml'
'template/etc/dionaea/ihandlers-available/tftp_download.yaml' -> './etc/dionaea/ihandlers-available/tftp_download.yaml'
'template/etc/dionaea/ihandlers-available/virustotal.yaml' -> './etc/dionaea/ihandlers-available/virustotal.yaml'
'template/etc/dionaea/services-available' -> './etc/dionaea/services-available'
'template/etc/dionaea/services-available/blackhole.yaml' -> './etc/dionaea/services-available/blackhole.yaml'
'template/etc/dionaea/services-available/epmap.yaml' -> './etc/dionaea/services-available/epmap.yaml'
'template/etc/dionaea/services-available/ftp.yaml' -> './etc/dionaea/services-available/ftp.yaml'
'template/etc/dionaea/services-available/http.yaml' -> './etc/dionaea/services-available/http.yaml'
'template/etc/dionaea/services-available/memcache.yaml' -> './etc/dionaea/services-available/memcache.yaml'
'template/etc/dionaea/services-available/mirror.yaml' -> './etc/dionaea/services-available/mirror.yaml'
'template/etc/dionaea/services-available/mongo.yaml' -> './etc/dionaea/services-available/mongo.yaml'
'template/etc/dionaea/services-available/mqtt.yaml' -> './etc/dionaea/services-available/mqtt.yaml'
'template/etc/dionaea/services-available/mssql.yaml' -> './etc/dionaea/services-available/mssql.yaml'
'template/etc/dionaea/services-available/mysql.yaml' -> './etc/dionaea/services-available/mysql.yaml'
'template/etc/dionaea/services-available/pptp.yaml' -> './etc/dionaea/services-available/pptp.yaml'
'template/etc/dionaea/services-available/printer.yaml' -> './etc/dionaea/services-available/printer.yaml'
'template/etc/dionaea/services-available/sip.yaml' -> './etc/dionaea/services-available/sip.yaml'
'template/etc/dionaea/services-available/smb.yaml' -> './etc/dionaea/services-available/smb.yaml'
'template/etc/dionaea/services-available/tftp.yaml' -> './etc/dionaea/services-available/tftp.yaml'
'template/etc/dionaea/services-available/upnp.yaml' -> './etc/dionaea/services-available/upnp.yaml'
'template/etc/dionaea/dionaea.cfg' -> './etc/dionaea/dionaea.cfg'
'template/etc/dionaea/ihandlers-enabled' -> './etc/dionaea/ihandlers-enabled'
'template/etc/dionaea/ihandlers-enabled/cmdshell.yaml' -> './etc/dionaea/ihandlers-enabled/cmdshell.yaml'
'template/etc/dionaea/ihandlers-enabled/emuprofile.yaml' -> './etc/dionaea/ihandlers-enabled/emuprofile.yaml'
'template/etc/dionaea/ihandlers-enabled/ftp.yaml' -> './etc/dionaea/ihandlers-enabled/ftp.yaml'
'template/etc/dionaea/ihandlers-enabled/log_sqlite.yaml' -> './etc/dionaea/ihandlers-enabled/log_sqlite.yaml'
'template/etc/dionaea/ihandlers-enabled/store.yaml' -> './etc/dionaea/ihandlers-enabled/store.yaml'
'template/etc/dionaea/ihandlers-enabled/tftp_download.yaml' -> './etc/dionaea/ihandlers-enabled/tftp_download.yaml'
'template/etc/dionaea/services-enabled' -> './etc/dionaea/services-enabled'
'template/etc/dionaea/services-enabled/blackhole.yaml' -> './etc/dionaea/services-enabled/blackhole.yaml'
'template/etc/dionaea/services-enabled/epmap.yaml' -> './etc/dionaea/services-enabled/epmap.yaml'
'template/etc/dionaea/services-enabled/ftp.yaml' -> './etc/dionaea/services-enabled/ftp.yaml'
'template/etc/dionaea/services-enabled/http.yaml' -> './etc/dionaea/services-enabled/http.yaml'
'template/etc/dionaea/services-enabled/memcache.yaml' -> './etc/dionaea/services-enabled/memcache.yaml'
'template/etc/dionaea/services-enabled/mirror.yaml' -> './etc/dionaea/services-enabled/mirror.yaml'
'template/etc/dionaea/services-enabled/mongo.yaml' -> './etc/dionaea/services-enabled/mongo.yaml'
'template/etc/dionaea/services-enabled/mqtt.yaml' -> './etc/dionaea/services-enabled/mqtt.yaml'
'template/etc/dionaea/services-enabled/mssql.yaml' -> './etc/dionaea/services-enabled/mssql.yaml'
'template/etc/dionaea/services-enabled/mysql.yaml' -> './etc/dionaea/services-enabled/mysql.yaml'
'template/etc/dionaea/services-enabled/pptp.yaml' -> './etc/dionaea/services-enabled/pptp.yaml'
'template/etc/dionaea/services-enabled/printer.yaml' -> './etc/dionaea/services-enabled/printer.yaml'
'template/etc/dionaea/services-enabled/sip.yaml' -> './etc/dionaea/services-enabled/sip.yaml'
'template/etc/dionaea/services-enabled/smb.yaml' -> './etc/dionaea/services-enabled/smb.yaml'
'template/etc/dionaea/services-enabled/tftp.yaml' -> './etc/dionaea/services-enabled/tftp.yaml'
'template/etc/dionaea/services-enabled/upnp.yaml' -> './etc/dionaea/services-enabled/upnp.yaml'
'template/lib' -> 'var/lib'
'template/lib/dionaea' -> 'var/lib/dionaea'
'template/lib/dionaea/binaries' -> 'var/lib/dionaea/binaries'
'template/lib/dionaea/fail2ban' -> 'var/lib/dionaea/fail2ban'
'template/lib/dionaea/printer' -> 'var/lib/dionaea/printer'
'template/lib/dionaea/printer/root' -> 'var/lib/dionaea/printer/root'
'template/lib/dionaea/printer/root/0' -> 'var/lib/dionaea/printer/root/0'
'template/lib/dionaea/bistreams' -> 'var/lib/dionaea/bistreams'
'template/lib/dionaea/ftp' -> 'var/lib/dionaea/ftp'
'template/lib/dionaea/ftp/root' -> 'var/lib/dionaea/ftp/root'
'template/lib/dionaea/http' -> 'var/lib/dionaea/http'
'template/lib/dionaea/http/root' -> 'var/lib/dionaea/http/root'
'template/lib/dionaea/http/template' -> 'var/lib/dionaea/http/template'
'template/lib/dionaea/http/template/example' -> 'var/lib/dionaea/http/template/example'
'template/lib/dionaea/http/template/example/form.html.j2' -> 'var/lib/dionaea/http/template/example/form.html.j2'
'template/lib/dionaea/http/template/nginx' -> 'var/lib/dionaea/http/template/nginx'
'template/lib/dionaea/http/template/nginx/autoindex.html.j2' -> 'var/lib/dionaea/http/template/nginx/autoindex.html.j2'
'template/lib/dionaea/http/template/nginx/error.html.j2' -> 'var/lib/dionaea/http/template/nginx/error.html.j2'
'template/lib/dionaea/sip' -> 'var/lib/dionaea/sip'
'template/lib/dionaea/sip/rtp' -> 'var/lib/dionaea/sip/rtp'
'template/lib/dionaea/tftp' -> 'var/lib/dionaea/tftp'
'template/lib/dionaea/tftp/root' -> 'var/lib/dionaea/tftp/root'
'template/lib/dionaea/upnp' -> 'var/lib/dionaea/upnp'
'template/lib/dionaea/upnp/root' -> 'var/lib/dionaea/upnp/root'
'template/log' -> 'var/log'
'template/log/dionaea' -> 'var/log/dionaea'
Starting dionaea ...

Dionaea Version 0.11.0
Compiled on Linux/x86_64 at Nov 30 2020 22:09:53 with gcc 7.5.0
Started on 74a918263fd9 running Linux/x86_64 release 6.1.124-134.200.amzn2023.x86_64

[28012025 06:42:23] pptp /dionaea/pptp/pptp.py:52: No config provided. Using default values
[28012025 06:42:23] services /dionaea/services.py:46: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
[28012025 06:42:23] pptp /dionaea/pptp/pptp.py:52: No config provided. Using default values
[28012025 06:42:23] services /dionaea/services.py:46: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
[28012025 06:45:33] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 06:45:33] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 06:55:25] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 06:55:25] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 06:59:11] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 07:00:41] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 07:00:41] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 07:01:10] ftp /dionaea/ftp.py:235: cmd 'b'HELP''
[28012025 07:01:12] ftp /dionaea/ftp.py:235: cmd 'b'SYST''
[28012025 07:01:14] ftp /dionaea/ftp.py:235: cmd 'b'FEAT''
[28012025 07:01:16] ftp /dionaea/ftp.py:235: cmd 'b'QUIT''
[28012025 07:13:45] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 07:13:46] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 07:28:26] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 07:47:26] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 07:47:26] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 07:50:43] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 08:21:40] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 08:21:51] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 08:25:13] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 08:29:58] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'\x00'
[28012025 08:29:58] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'\x00'
[28012025 08:29:58] SMB /dionaea/smb/smb.py:107: === not really SMB
[28012025 08:31:11] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 08:39:26] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 08:44:18] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 08:49:55] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 08:50:12] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 08:50:13] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 08:50:13] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 08:50:14] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 08:50:14] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 08:50:14] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 09:29:45] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 09:37:40] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 09:37:40] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 09:38:55] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 09:43:17] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 09:43:18] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 09:43:33] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 09:50:46] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 10:11:46] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 10:24:37] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 10:38:41] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 10:38:41] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 10:47:57] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 10:47:57] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 11:11:25] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 11:11:25] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 11:15:19] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 11:17:37] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 11:20:36] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 11:25:00] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 11:29:26] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 11:29:26] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 11:32:56] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 11:32:56] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[28012025 11:32:56] root (unknown file):0: There was an error in the Python service
Traceback (most recent call last):
  File "binding.pyx", line 778, in dionaea.core.handle_io_in_cb
  File "lib/dionaea/python/dionaea/http.py", line 589, in handle_io_in
    self.handle_POST()
  File "lib/dionaea/python/dionaea/http.py", line 702, in handle_POST
    environ=tmp_environ
  File "/usr/lib/python3.6/cgi.py", line 566, in __init__
    self.read_single()
  File "/usr/lib/python3.6/cgi.py", line 757, in read_single
    self.read_binary()
  File "/usr/lib/python3.6/cgi.py", line 779, in read_binary
    self.file.write(data)
TypeError: write() argument must be str, not bytes
[28012025 11:40:29] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 11:40:29] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[28012025 11:40:29] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 11:40:29] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 11:42:33] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 11:47:14] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 11:52:38] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:01:53] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:02:15] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:23:12] connection /code/src/connection_tcp.c:271: recv failed size -1 recv_size 1 (Connection reset by peer)
[28012025 12:31:44] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 12:31:44] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 12:32:26] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:33:13] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 12:33:16] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:33:21] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:33:22] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:33:24] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:33:34] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 12:38:19] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:43:18] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:44:05] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:47:25] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 12:47:25] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 12:49:09] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:57:29] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 12:58:35] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 13:12:17] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 13:17:46] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 13:32:09] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 13:55:54] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 14:33:45] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 14:35:04] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 14:35:06] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 14:35:06] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 14:35:07] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 14:35:09] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 14:35:09] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 14:35:10] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 14:35:11] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 14:35:12] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 14:35:12] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 14:44:16] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 14:57:28] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 14:59:28] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 15:02:17] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 15:02:56] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 15:02:56] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 15:05:10] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 15:09:17] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 15:36:05] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 15:36:45] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 15:43:58] SMB /dionaea/smb/smb.py:107: === not really SMB
[28012025 15:58:18] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 15:58:18] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 16:08:40] connection /code/src/connection_tcp.c:271: recv failed size -1 recv_size 1 (Connection reset by peer)
[28012025 16:10:04] connection /code/src/connection_tcp.c:271: recv failed size -1 recv_size 1 (Connection reset by peer)
[28012025 16:23:26] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 16:28:56] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 16:33:48] ftp /dionaea/ftp.py:235: cmd 'b'AUTH''
[28012025 16:45:15] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 16:49:46] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 16:52:17] ftp /dionaea/ftp.py:235: cmd 'b'USER''
[28012025 16:52:17] ftp /dionaea/ftp.py:235: cmd 'b'PASS''
[28012025 16:52:17] ftp /dionaea/ftp.py:235: cmd 'b'OPTS''
[28012025 16:52:17] ftp /dionaea/ftp.py:235: cmd 'b'PWD''
[28012025 16:52:17] ftp /dionaea/ftp.py:235: cmd 'b'TYPE''
[28012025 17:01:29] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 17:01:30] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 17:07:33] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 17:07:35] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 17:07:35] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 17:07:36] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 17:07:37] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 17:07:37] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 17:07:38] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 17:07:39] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 17:08:08] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 17:08:41] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 17:08:41] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 17:08:49] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 17:09:14] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 17:09:47] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 17:10:20] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 17:10:53] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 17:11:26] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 17:11:59] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 17:12:32] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 17:17:35] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 17:17:35] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 17:23:22] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 17:40:57] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 17:40:57] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 17:48:40] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 17:58:21] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 18:01:48] connection /code/src/connection_tcp.c:271: recv failed size -1 recv_size 1 (Connection reset by peer)
[28012025 18:01:51] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 18:01:55] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 18:01:55] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 18:01:56] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 18:14:07] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 18:38:14] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 18:41:27] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 18:41:35] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 18:41:43] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 18:41:47] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 18:41:49] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 18:42:04] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 19:05:01] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 19:05:01] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 19:07:05] connection /code/src/connection_tcp.c:271: recv failed size -1 recv_size 1 (Connection reset by peer)
[28012025 19:11:42] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 19:11:43] connection /code/src/connection_tcp.c:271: recv failed size -1 recv_size 1 (Connection reset by peer)
[28012025 19:11:51] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 19:11:51] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 19:11:52] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 19:11:55] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 19:11:57] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 19:11:59] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 19:12:02] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 19:12:04] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 19:12:06] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 19:12:09] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 19:12:11] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 19:12:13] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 19:24:54] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 19:30:55] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 19:30:55] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[28012025 19:30:55] root (unknown file):0: There was an error in the Python service
Traceback (most recent call last):
  File "binding.pyx", line 778, in dionaea.core.handle_io_in_cb
  File "lib/dionaea/python/dionaea/http.py", line 589, in handle_io_in
    self.handle_POST()
  File "lib/dionaea/python/dionaea/http.py", line 702, in handle_POST
    environ=tmp_environ
  File "/usr/lib/python3.6/cgi.py", line 566, in __init__
    self.read_single()
  File "/usr/lib/python3.6/cgi.py", line 757, in read_single
    self.read_binary()
  File "/usr/lib/python3.6/cgi.py", line 779, in read_binary
    self.file.write(data)
TypeError: write() argument must be str, not bytes
[28012025 19:35:17] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 19:35:17] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 19:46:13] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 19:50:01] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 19:52:36] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 20:01:38] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:01:39] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:01:39] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:01:40] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:01:40] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:01:40] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:01:41] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:01:41] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:01:41] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:01:42] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:17:32] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 20:24:56] ftp /dionaea/ftp.py:235: cmd 'b'MGLNDD_13.60.167.146_21''
[28012025 20:26:23] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:36:53] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 20:37:17] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:18] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:29] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:29] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 20:37:30] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 20:37:31] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 20:37:32] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 20:37:33] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:34] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:34] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:36] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:37] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:37] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:38] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:39] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:39] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:40] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 20:37:40] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 20:37:41] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 20:49:00] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 20:49:02] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 21:16:57] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 21:28:31] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 21:29:10] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 21:33:55] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 21:41:54] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 21:46:08] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 21:46:09] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 21:46:28] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 21:52:13] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 21:55:04] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:00:47] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:30:49] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:33:08] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 22:33:08] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[28012025 22:34:19] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:34:19] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:34:19] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[28012025 22:34:20] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:34:21] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:34:21] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[28012025 22:34:22] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:46:35] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:49:55] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:52:01] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:53:41] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:55:01] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 22:58:52] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 23:01:37] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 23:01:37] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 23:01:38] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 23:01:39] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:40] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:40] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:41] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:41] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:42] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:42] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:43] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:43] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:43] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:44] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:44] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 23:01:45] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 23:01:45] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:45] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[28012025 23:01:45] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 23:01:46] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 23:01:47] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 23:03:07] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 23:19:05] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[28012025 23:54:09] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 00:02:52] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 00:02:53] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 00:02:54] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 00:02:54] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 00:02:54] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 00:02:55] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 00:02:55] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 00:02:55] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 00:02:56] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 00:02:56] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 00:02:56] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 00:02:57] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 00:05:14] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 00:16:30] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 00:16:31] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 00:28:56] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 01:10:11] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 01:16:53] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 01:17:04] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 01:18:08] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 01:23:20] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 01:23:31] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 01:33:07] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 01:50:30] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 02:23:48] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:23:49] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:23:49] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:23:50] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:23:50] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:23:50] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:23:51] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:23:51] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:23:52] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:23:52] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:25:31] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:25:32] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:25:32] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:25:33] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:25:33] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:25:33] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:25:34] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:25:34] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:25:34] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:25:34] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 02:43:29] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 02:46:01] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 02:48:40] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 02:50:17] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 03:14:55] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 03:24:26] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 03:40:20] SMB /dionaea/smb/smb.py:107: === not really SMB
[29012025 03:40:58] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 03:41:33] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 03:46:19] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 03:46:45] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 03:46:45] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 03:56:13] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 04:25:08] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 04:25:13] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 04:31:46] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 04:31:46] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 04:36:02] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 04:36:02] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 04:37:57] SMB /dionaea/smb/smb.py:107: === not really SMB
[29012025 04:43:59] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 04:43:59] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 05:02:48] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:03:18] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 05:03:18] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 05:07:18] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 05:07:18] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 05:07:25] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 05:07:25] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 05:14:43] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:14:43] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:21:41] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:29:36] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 05:29:36] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 05:32:27] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:32:28] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:32:29] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:32:30] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:30] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:30] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:31] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:32] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:32] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:33] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:34] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:34] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:34] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:34] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:32:34] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:35] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:32:35] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:36] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:32:36] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 05:32:37] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:32:37] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:46:17] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 05:46:17] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 05:48:27] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:49:57] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:51:00] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:51:58] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 05:52:18] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 06:03:07] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 06:03:07] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 06:35:03] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 06:52:17] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 06:52:17] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 06:57:48] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 07:18:05] connection /code/src/connection_tcp.c:271: recv failed size -1 recv_size 1 (Connection reset by peer)
[29012025 07:18:08] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 07:18:11] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 07:18:11] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 07:18:11] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 07:24:12] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 07:24:14] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 07:25:56] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 07:41:11] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 07:46:22] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 07:47:51] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 07:53:15] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 07:58:55] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 07:58:57] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 07:59:10] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 08:04:13] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 08:23:28] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 08:23:28] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 08:27:48] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 08:27:48] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 08:35:29] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 08:35:29] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 08:37:45] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 08:57:04] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 09:21:08] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 09:30:52] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 09:30:52] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 09:32:58] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 09:36:12] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 09:47:29] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 09:47:31] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 09:47:32] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 09:49:48] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 09:55:05] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 10:01:36] ftp /dionaea/ftp.py:235: cmd 'b'AUTH''
[29012025 10:01:36] ftp /dionaea/ftp.py:235: cmd 'b'AUTH''
[29012025 11:07:12] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'\x00'
[29012025 11:07:12] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'\x00'
[29012025 11:15:26] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 11:15:26] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 11:27:15] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 11:38:39] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 11:38:39] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 11:42:02] connection /code/src/connection_tcp.c:271: recv failed size -1 recv_size 1 (Connection reset by peer)
[29012025 11:42:06] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 11:42:15] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 11:42:16] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 11:42:17] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 11:43:58] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 11:49:52] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:31:17] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:31:31] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:31:31] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:31:31] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:31:31] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:31:31] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:31:32] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:31:32] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:31:32] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:31:32] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:40:45] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 12:44:49] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:44:50] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:44:50] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[29012025 12:44:50] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:55:57] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 12:58:36] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 13:15:00] ftp /dionaea/ftp.py:235: cmd 'b'USER''
[29012025 13:15:00] ftp /dionaea/ftp.py:235: cmd 'b'PASS''
[29012025 13:15:00] ftp /dionaea/ftp.py:235: cmd 'b'OPTS''
[29012025 13:15:00] ftp /dionaea/ftp.py:235: cmd 'b'PWD''
[29012025 13:15:00] ftp /dionaea/ftp.py:235: cmd 'b'TYPE''
[29012025 13:31:31] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 13:39:36] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 13:39:36] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[29012025 13:39:36] root (unknown file):0: There was an error in the Python service
Traceback (most recent call last):
  File "binding.pyx", line 778, in dionaea.core.handle_io_in_cb
  File "lib/dionaea/python/dionaea/http.py", line 589, in handle_io_in
    self.handle_POST()
  File "lib/dionaea/python/dionaea/http.py", line 702, in handle_POST
    environ=tmp_environ
  File "/usr/lib/python3.6/cgi.py", line 566, in __init__
    self.read_single()
  File "/usr/lib/python3.6/cgi.py", line 757, in read_single
    self.read_binary()
  File "/usr/lib/python3.6/cgi.py", line 779, in read_binary
    self.file.write(data)
TypeError: write() argument must be str, not bytes
[29012025 13:41:16] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 13:51:22] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 13:55:44] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 14:03:06] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 14:03:06] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 14:13:07] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 14:13:32] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 14:17:30] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 14:29:30] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 14:36:24] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 14:45:11] ftp /dionaea/ftp.py:235: cmd 'b'USER''
[29012025 14:46:21] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 14:46:55] ftp /dionaea/ftp.py:235: cmd 'b'PASS''
[29012025 14:59:29] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:07:26] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 15:12:56] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 15:16:47] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 15:16:47] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 15:17:39] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:17:41] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:17:44] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:17:53] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 15:17:55] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 15:17:55] root (unknown file):0: There was an error in the Python service
Traceback (most recent call last):
  File "binding.pyx", line 778, in dionaea.core.handle_io_in_cb
  File "lib/dionaea/python/dionaea/http.py", line 524, in handle_io_in
    self.header = httpreq(header, self)
  File "lib/dionaea/python/dionaea/http.py", line 141, in __init__
    self.version = reqparts[2]
IndexError: list index out of range
[29012025 15:17:56] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:17:57] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:17:58] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:17:58] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:17:59] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:18:00] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:18:00] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:18:01] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:18:01] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:18:02] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:18:02] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 15:18:25] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 15:18:26] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 15:18:27] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 15:18:27] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 15:26:51] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 15:33:20] SMB /dionaea/smb/smb.py:107: === not really SMB
[29012025 15:46:33] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 15:46:33] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 15:48:32] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 15:48:34] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 15:48:42] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 15:54:49] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'\x00'
[29012025 15:54:49] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'\x00'
[29012025 15:54:49] SMB /dionaea/smb/smb.py:107: === not really SMB
[29012025 16:15:36] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 16:17:57] connection /code/src/connection_tcp.c:271: recv failed size -1 recv_size 1 (Connection reset by peer)
[29012025 16:27:36] SMB /dionaea/smb/smb.py:107: === not really SMB
[29012025 16:27:44] SMB /dionaea/smb/smb.py:107: === not really SMB
[29012025 16:29:40] SMB /dionaea/smb/smb.py:107: === not really SMB
[29012025 16:45:00] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 16:45:00] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 16:56:13] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 16:56:13] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 16:56:39] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 17:05:05] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 17:05:05] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 17:10:05] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:16:40] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:18:06] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:18:06] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:18:07] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:18:07] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:18:11] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:18:15] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:18:56] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:18:57] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:19:34] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:19:34] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[29012025 17:19:34] root (unknown file):0: There was an error in the Python service
Traceback (most recent call last):
  File "binding.pyx", line 778, in dionaea.core.handle_io_in_cb
  File "lib/dionaea/python/dionaea/http.py", line 589, in handle_io_in
    self.handle_POST()
  File "lib/dionaea/python/dionaea/http.py", line 702, in handle_POST
    environ=tmp_environ
  File "/usr/lib/python3.6/cgi.py", line 566, in __init__
    self.read_single()
  File "/usr/lib/python3.6/cgi.py", line 757, in read_single
    self.read_binary()
  File "/usr/lib/python3.6/cgi.py", line 779, in read_binary
    self.file.write(data)
TypeError: write() argument must be str, not bytes
[29012025 17:19:35] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:19:35] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[29012025 17:19:35] root (unknown file):0: There was an error in the Python service
Traceback (most recent call last):
  File "binding.pyx", line 778, in dionaea.core.handle_io_in_cb
  File "lib/dionaea/python/dionaea/http.py", line 637, in handle_io_in
    self.handle_POST()
  File "lib/dionaea/python/dionaea/http.py", line 702, in handle_POST
    environ=tmp_environ
  File "/usr/lib/python3.6/cgi.py", line 566, in __init__
    self.read_single()
  File "/usr/lib/python3.6/cgi.py", line 757, in read_single
    self.read_binary()
  File "/usr/lib/python3.6/cgi.py", line 779, in read_binary
    self.file.write(data)
TypeError: write() argument must be str, not bytes
[29012025 17:41:02] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:56:05] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:56:06] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 17:59:51] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 17:59:51] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 18:04:44] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 18:14:35] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 18:23:29] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 18:46:47] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 18:46:48] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 18:48:34] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 18:48:34] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 18:54:41] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 18:57:05] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 18:58:54] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 19:00:35] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 19:06:07] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 19:06:07] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 19:15:34] ftp /dionaea/ftp.py:235: cmd 'b'AUTH''
[29012025 19:15:34] ftp /dionaea/ftp.py:235: cmd 'b'AUTH''
[29012025 19:22:39] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 19:22:39] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[29012025 19:22:39] root (unknown file):0: There was an error in the Python service
Traceback (most recent call last):
  File "binding.pyx", line 778, in dionaea.core.handle_io_in_cb
  File "lib/dionaea/python/dionaea/http.py", line 589, in handle_io_in
    self.handle_POST()
  File "lib/dionaea/python/dionaea/http.py", line 702, in handle_POST
    environ=tmp_environ
  File "/usr/lib/python3.6/cgi.py", line 566, in __init__
    self.read_single()
  File "/usr/lib/python3.6/cgi.py", line 757, in read_single
    self.read_binary()
  File "/usr/lib/python3.6/cgi.py", line 779, in read_binary
    self.file.write(data)
TypeError: write() argument must be str, not bytes
[29012025 19:24:22] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 19:27:05] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 19:51:12] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 19:58:28] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 19:59:57] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 20:19:39] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 20:19:39] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 20:21:42] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 20:23:11] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 20:23:11] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[29012025 20:23:11] root (unknown file):0: There was an error in the Python service
Traceback (most recent call last):
  File "binding.pyx", line 778, in dionaea.core.handle_io_in_cb
read: Connection reset by peer
  File "lib/dionaea/python/dionaea/http.py", line 589, in handle_io_in
    self.handle_POST()
  File "lib/dionaea/python/dionaea/http.py", line 702, in handle_POST
    environ=tmp_environ
  File "/usr/lib/python3.6/cgi.py", line 566, in __init__
    self.read_single()
  File "/usr/lib/python3.6/cgi.py", line 757, in read_single
    self.read_binary()
  File "/usr/lib/python3.6/cgi.py", line 779, in read_binary
    self.file.write(data)
TypeError: write() argument must be str, not bytes
[29012025 20:25:17] ftp /dionaea/ftp.py:235: cmd 'b'AUTH''
[29012025 20:25:18] ftp /dionaea/ftp.py:235: cmd 'b'AUTH''
[29012025 20:25:26] SMB /dionaea/smb/smb.py:127: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 20:25:26] SMB /dionaea/smb/smb.py:157: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[29012025 20:30:22] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 20:31:59] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 20:31:59] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[29012025 20:37:46] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 20:43:10] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 20:47:31] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 20:53:05] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 21:23:44] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 21:23:45] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 21:28:24] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 21:28:26] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 21:28:26] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 21:28:27] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 21:28:29] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 21:28:29] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 21:28:30] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 21:28:32] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 21:28:32] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 21:28:33] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 21:30:35] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 21:36:24] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 21:43:39] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 21:45:33] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 21:50:33] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 21:55:27] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 21:55:28] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 22:09:32] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 22:20:18] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 22:20:18] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 22:20:18] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 22:20:18] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[29012025 22:35:02] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 22:35:02] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 22:43:03] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 22:45:02] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 22:48:08] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 22:49:01] SMB /dionaea/smb/smb.py:107: === not really SMB
[29012025 22:54:03] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 22:58:08] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 23:09:42] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[29012025 23:53:16] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 00:04:40] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 00:04:51] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 00:04:51] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 00:04:51] http /dionaea/http.py:699: max_num_fields is only supported with Python >= 3.8
[30012025 00:29:29] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 00:29:30] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 00:29:32] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 00:29:48] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 00:40:42] ftp /dionaea/ftp.py:235: cmd 'b'AUTH''
[30012025 00:40:42] ftp /dionaea/ftp.py:235: cmd 'b'AUTH''
[30012025 00:43:01] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 00:43:08] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 00:47:55] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 00:54:31] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 00:54:31] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 01:26:58] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 01:27:15] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 01:31:23] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 01:31:51] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 01:32:21] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8
[30012025 01:33:48] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 01:33:49] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 01:33:49] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 01:33:50] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 01:33:51] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 01:33:51] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 01:33:52] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 01:33:53] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 01:33:53] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 01:33:53] log_sqlite /dionaea/logsql.py:747: no attackid for 172.17.0.2:443
[30012025 01:37:08] http /dionaea/http.py:133: max_num_fields is only supported with Python >= 3.8